/**
 * Weaviate object types
 *
 * This module defines types for Weaviate objects and their CRUD operations.
 */

import type { UUID, Properties } from './property.js';
import type { Vector } from './vector.js';
import type { WhereFilter } from './filter.js';

/**
 * Consistency level for operations
 *
 * Determines how many replicas must acknowledge an operation
 * before it is considered successful.
 */
export enum ConsistencyLevel {
  /**
   * Only one replica must acknowledge (fastest, least consistent)
   */
  One = 'ONE',

  /**
   * Majority of replicas must acknowledge (balanced)
   */
  Quorum = 'QUORUM',

  /**
   * All replicas must acknowledge (slowest, most consistent)
   */
  All = 'ALL',
}

/**
 * A Weaviate object
 *
 * Represents a single data object in Weaviate with its properties,
 * vector, and metadata.
 *
 * @example
 * ```typescript
 * const article: WeaviateObject = {
 *   id: "123e4567-e89b-12d3-a456-426614174000" as UUID,
 *   className: "Article",
 *   properties: {
 *     title: "Introduction to Vector Databases",
 *     content: "Vector databases are...",
 *     publishedDate: new Date("2024-01-15"),
 *     tags: ["database", "ai", "vectors"]
 *   },
 *   vector: [0.1, 0.2, 0.3, ...],
 *   creationTime: new Date("2024-01-15T10:00:00Z"),
 *   updateTime: new Date("2024-01-15T10:00:00Z")
 * };
 * ```
 */
export interface WeaviateObject {
  /**
   * Unique identifier (UUID v4)
   */
  id: UUID;

  /**
   * Name of the class this object belongs to
   */
  className: string;

  /**
   * Object properties (schema-defined fields)
   */
  properties: Properties;

  /**
   * Vector embedding (optional, can be generated by vectorizer)
   */
  vector?: Vector;

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * When the object was created (ISO 8601 timestamp)
   */
  creationTime?: Date;

  /**
   * When the object was last updated (ISO 8601 timestamp)
   */
  updateTime?: Date;

  /**
   * Additional metadata returned by Weaviate
   */
  additional?: Record<string, unknown>;
}

/**
 * Options for creating a new object
 *
 * @example
 * ```typescript
 * const options: CreateOptions = {
 *   className: "Article",
 *   properties: {
 *     title: "My Article",
 *     content: "Article content..."
 *   },
 *   vector: [0.1, 0.2, 0.3, ...],
 *   id: "custom-uuid" as UUID,
 *   tenant: "tenant-a"
 * };
 * ```
 */
export interface CreateOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Object properties
   */
  properties: Properties;

  /**
   * Vector embedding (optional if vectorizer is configured)
   */
  vector?: Vector;

  /**
   * Custom UUID (auto-generated if not provided)
   */
  id?: UUID;

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * Consistency level for this operation
   */
  consistencyLevel?: ConsistencyLevel;
}

/**
 * Options for retrieving an object
 *
 * @example
 * ```typescript
 * const options: GetOptions = {
 *   className: "Article",
 *   id: "123e4567-e89b-12d3-a456-426614174000" as UUID,
 *   includeVector: true,
 *   tenant: "tenant-a"
 * };
 * ```
 */
export interface GetOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Object UUID
   */
  id: UUID;

  /**
   * Whether to include the vector in the response
   */
  includeVector?: boolean;

  /**
   * Specific properties to return (returns all if not specified)
   */
  properties?: string[];

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * Consistency level for this operation
   */
  consistencyLevel?: ConsistencyLevel;

  /**
   * Node name to read from (for directed reads)
   */
  nodeName?: string;
}

/**
 * Options for updating an object
 *
 * @example
 * ```typescript
 * const options: UpdateOptions = {
 *   className: "Article",
 *   id: "123e4567-e89b-12d3-a456-426614174000" as UUID,
 *   properties: {
 *     title: "Updated Title"
 *   },
 *   merge: true
 * };
 * ```
 */
export interface UpdateOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Object UUID
   */
  id: UUID;

  /**
   * Properties to update
   */
  properties?: Properties;

  /**
   * Vector to update
   */
  vector?: Vector;

  /**
   * Whether to merge with existing properties (true) or replace (false)
   * Default: true (merge)
   */
  merge?: boolean;

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * Consistency level for this operation
   */
  consistencyLevel?: ConsistencyLevel;
}

/**
 * Options for deleting an object
 *
 * @example
 * ```typescript
 * const options: DeleteOptions = {
 *   className: "Article",
 *   id: "123e4567-e89b-12d3-a456-426614174000" as UUID,
 *   tenant: "tenant-a"
 * };
 * ```
 */
export interface DeleteOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Object UUID
   */
  id: UUID;

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * Consistency level for this operation
   */
  consistencyLevel?: ConsistencyLevel;
}

/**
 * Options for checking if an object exists
 */
export interface ExistsOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Object UUID
   */
  id: UUID;

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * Consistency level for this operation
   */
  consistencyLevel?: ConsistencyLevel;
}

/**
 * Options for validating an object against schema
 */
export interface ValidateOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Properties to validate
   */
  properties: Properties;

  /**
   * Vector to validate
   */
  vector?: Vector;
}

/**
 * Validation result
 */
export interface ValidationResult {
  /**
   * Whether the object is valid
   */
  valid: boolean;

  /**
   * Validation error messages (if any)
   */
  errors?: string[];
}

/**
 * List objects options
 */
export interface ListOptions {
  /**
   * Name of the class
   */
  className: string;

  /**
   * Maximum number of objects to return
   */
  limit?: number;

  /**
   * Number of objects to skip
   */
  offset?: number;

  /**
   * Filter to apply
   */
  filter?: WhereFilter;

  /**
   * Specific properties to return
   */
  properties?: string[];

  /**
   * Whether to include vectors
   */
  includeVector?: boolean;

  /**
   * Tenant name for multi-tenant collections
   */
  tenant?: string;

  /**
   * Cursor for pagination (alternative to offset)
   */
  after?: string;

  /**
   * Sort configuration
   */
  sort?: SortOptions[];
}

/**
 * Sort options for listing objects
 */
export interface SortOptions {
  /**
   * Property path to sort by
   */
  path: string[];

  /**
   * Sort order
   */
  order?: 'asc' | 'desc';
}

/**
 * List objects response
 */
export interface ListResponse {
  /**
   * Retrieved objects
   */
  objects: WeaviateObject[];

  /**
   * Total count of objects matching the filter (if available)
   */
  totalCount?: number;

  /**
   * Cursor for next page (if available)
   */
  nextCursor?: string;
}
