/**
 * Types for the Chat service.
 */

import type { ApiMeta, FinishReason, GenerationOptions, ConnectorConfig } from '../../types';

/**
 * Message role in a conversation
 */
export type MessageRole = 'USER' | 'CHATBOT' | 'SYSTEM' | 'TOOL';

/**
 * Chat message
 */
export interface ChatMessage {
  role: MessageRole;
  content: string;
  name?: string;
  toolCallId?: string;
}

/**
 * Tool parameter definition
 */
export interface ToolParameter {
  name: string;
  description: string;
  type: string;
  required?: boolean;
}

/**
 * Tool definition
 */
export interface Tool {
  name: string;
  description: string;
  parameters?: ToolParameter[];
}

/**
 * Tool call from the model
 */
export interface ToolCall {
  id: string;
  name: string;
  parameters: Record<string, unknown>;
}

/**
 * Result from a tool execution
 */
export interface ToolResult {
  callId: string;
  output: unknown;
}

/**
 * Document for RAG
 */
export interface Document {
  id?: string;
  title?: string;
  text: string;
  url?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Citation from source documents
 */
export interface Citation {
  start: number;
  end: number;
  text: string;
  documentIds: string[];
}

/**
 * Search query generated by the model
 */
export interface SearchQuery {
  text: string;
  generationId?: string;
}

/**
 * Search result from connectors
 */
export interface SearchResult {
  searchQuery?: SearchQuery;
  connector?: ConnectorConfig;
  documentIds: string[];
  results?: Document[];
}

/**
 * Chat request
 */
export interface ChatRequest extends GenerationOptions {
  /** The message to send */
  message: string;
  /** Model to use */
  model?: string;
  /** Preamble/system message */
  preamble?: string;
  /** Conversation history */
  chatHistory?: ChatMessage[];
  /** Conversation ID for multi-turn */
  conversationId?: string;
  /** Tools available to the model */
  tools?: Tool[];
  /** Tool results from previous calls */
  toolResults?: ToolResult[];
  /** Force tool use */
  forceSingleStep?: boolean;
  /** Documents for RAG */
  documents?: Document[];
  /** Connectors for search */
  connectors?: ConnectorConfig[];
  /** Citation quality */
  citationQuality?: 'accurate' | 'fast';
  /** Prompt truncation strategy */
  promptTruncation?: 'AUTO' | 'OFF';
  /** Search queries override */
  searchQueriesOnly?: boolean;
  /** Return prompt */
  returnPrompt?: boolean;
  /** Return preamble */
  returnPreamble?: boolean;
  /** Raw prompting (disable templates) */
  rawPrompting?: boolean;
}

/**
 * Chat response
 */
export interface ChatResponse {
  /** Generated text */
  text: string;
  /** Generation ID */
  generationId?: string;
  /** Finish reason */
  finishReason?: FinishReason;
  /** Updated chat history */
  chatHistory?: ChatMessage[];
  /** Tool calls requested */
  toolCalls?: ToolCall[];
  /** Citations */
  citations?: Citation[];
  /** Documents used */
  documents?: Document[];
  /** Search queries */
  searchQueries?: SearchQuery[];
  /** Search results */
  searchResults?: SearchResult[];
  /** API metadata */
  meta?: ApiMeta;
}

/**
 * Stream event types
 */
export type ChatStreamEventType =
  | 'stream-start'
  | 'text-generation'
  | 'citation-generation'
  | 'tool-calls-generation'
  | 'tool-calls-chunk'
  | 'search-queries-generation'
  | 'search-results'
  | 'stream-end';

/**
 * Chat stream event
 */
export interface ChatStreamEvent {
  eventType: ChatStreamEventType;
  /** Text chunk (for text-generation) */
  text?: string;
  /** Generation ID (for stream-start) */
  generationId?: string;
  /** Finish reason (for stream-end) */
  finishReason?: FinishReason;
  /** Tool calls (for tool-calls-generation) */
  toolCalls?: ToolCall[];
  /** Citations (for citation-generation) */
  citations?: Citation[];
  /** Search queries (for search-queries-generation) */
  searchQueries?: SearchQuery[];
  /** Search results (for search-results) */
  searchResults?: SearchResult[];
  /** Response (for stream-end) */
  response?: ChatResponse;
}

/**
 * Create a user message
 */
export function userMessage(content: string): ChatMessage {
  return { role: 'USER', content };
}

/**
 * Create a chatbot message
 */
export function chatbotMessage(content: string): ChatMessage {
  return { role: 'CHATBOT', content };
}

/**
 * Create a system message
 */
export function systemMessage(content: string): ChatMessage {
  return { role: 'SYSTEM', content };
}

/**
 * Create a tool result message
 */
export function toolMessage(content: string, toolCallId: string): ChatMessage {
  return { role: 'TOOL', content, toolCallId };
}
