/**
 * Validation utilities for Google Cloud Firestore.
 *
 * This module provides comprehensive validation for all Firestore-related
 * constraints including document IDs, paths, field paths, and size limits.
 *
 * Following the SPARC specification for the Firestore integration.
 *
 * @module validation
 */

// ============================================================================
// Document ID Validation
// ============================================================================

export {
  validateDocumentId,
  isValidDocumentId,
  generateDocumentId,
  sanitizeDocumentId,
  getSpecialCharacters,
  isAutoGeneratedId,
  MIN_DOCUMENT_ID_LENGTH,
  MAX_DOCUMENT_ID_LENGTH,
} from "./document-id.js";

// ============================================================================
// Document Path Validation
// ============================================================================

export {
  validateDocumentPath,
  isValidDocumentPath,
  parseDocumentPath,
  buildDocumentPath,
  buildDocumentName,
  parseDocumentName,
  getParentCollectionPath,
  getParentDocumentPath,
  getPathSegments,
  isNestedDocument,
  getDocumentDepth,
  normalizeDocumentPath,
} from "./document-path.js";

export type { DocumentPath, ValidatedDocumentPath } from "./document-path.js";

// ============================================================================
// Field Path Validation
// ============================================================================

export {
  validateFieldPath,
  isValidFieldPath,
  sanitizeFieldPath,
  expandFieldPath,
  joinFieldPath,
  getParentFieldPath,
  getFieldName,
  isTopLevelField,
  validateNestedMapDepth,
  getFieldValueDepth,
  isNestedField,
  createFieldPath,
  escapeFieldName,
  MAX_FIELD_DEPTH,
  MAX_FIELD_SEGMENT_LENGTH,
} from "./field-path.js";

export type { ValidatedFieldPath } from "./field-path.js";

// ============================================================================
// Size Limits Validation
// ============================================================================

export {
  calculateFieldSize,
  calculateDocumentSize,
  estimateDocumentSize,
  validateDocumentSize,
  validateBatchSize,
  validateTransactionSize,
  validateInClauseSize,
  validateOrClauseCount,
  validateListenerCount,
  validateArrayLength,
  isDocumentSizeNearLimit,
  getDocumentSizeStats,
  validateAllSizeConstraints,
  MAX_DOCUMENT_SIZE,
  MAX_BATCH_SIZE,
  MAX_TRANSACTION_OPERATIONS,
  MAX_TRANSACTION_DURATION_SEC,
  MAX_IN_CLAUSE_VALUES,
  MAX_OR_CLAUSES,
  MAX_LISTENERS,
  DOCUMENT_SIZE_WARNING_THRESHOLD,
  MAX_COLLECTION_ID_LENGTH,
  MAX_FIELD_PATH_SEGMENT_LENGTH,
  MAX_COMPOSITE_INDEXES_PER_COLLECTION,
  MAX_FIELDS_PER_COMPOSITE_INDEX,
  MAX_DOCUMENT_WRITE_RATE_PER_SEC,
  RECOMMENDED_MAX_ARRAY_LENGTH,
} from "./size-limits.js";
