export {
  type ChatRole,
  type ChatMessage,
  type ChatToolCall,
  type ChatFunctionCall,
  type ChatTool,
  type ChatFunctionDefinition,
  type ResponseFormat,
  type ChatCompletionRequest,
  type AzureDataSource,
  type ChatCompletionResponse,
  type ChatChoice,
  type ChatUsage,
  type ChatCompletionChunk,
  type ChatChunkChoice,
  type ChatDelta,
  type ChatToolCallDelta,
  type ChatCompletionService,
  type ChatServiceDependencies,
  toTokenUsage as chatToTokenUsage,
  createUserMessage,
  createSystemMessage,
  createAssistantMessage,
  ChatCompletionServiceImpl,
  ChatStreamAccumulator,
} from './chat/index.js';

export {
  type EmbeddingEncodingFormat,
  type EmbeddingRequest,
  type EmbeddingResponse,
  type Embedding,
  type EmbeddingUsage,
  type EmbeddingService,
  type EmbeddingServiceDependencies,
  toTokenUsage as embeddingToTokenUsage,
  decodeBase64Embedding,
  normalizeEmbeddings,
  EmbeddingServiceImpl,
  cosineSimilarity,
  euclideanDistance,
} from './embedding/index.js';
